name: fleets

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.15.4"
      - run: go run .
